### ISSUE TITLE
Self-referencing documentation (misrendered links?)

### ISSUE THREAD

**Issue by telefax** [gravitee-io/gravitee-docs#177]
On a few places, I have seen the documentation referencing back to it self when linking further, such as on this page: https://docs.gravitee.io/apim_overview_plugins.html

> They follow a given directory structure convention, look at the Developer Guide to have more information about it.

> Authorization using an API key (see the api-key policy)

> You can find more information by having a look to the Management API : Repository section."

And so on..

**Comment by plsstephenson** [comment]
This was fixed in latest rewrite.
