### ISSUE TITLE
How to install/enable SAML/CAS

### ISSUE THREAD

**Issue by frenchyjef** [gravitee-io/gravitee-docs#185]
Hi,

I found one of your [article](https://medium.com/graviteeio/gravitee-io-am-2-9-b010d16579ec) which states that support for SAML 2.0 Identity Providers is available starting with Access Management 2.9. 

However, I am unable to find documentation on how to install/enable SAML 2.0 support in Access Management. Could you provide a link or actual documentation explaining how we may enable support for SAML 2.0?

Cheers,
Jean-Francois

**Comment by brasseld** [comment]
Hi @frenchyjef,

SAML IDP is provided under our Gravitee.io Enterprise API Platform.

Cheers,

**Comment by plsstephenson** [comment]
In documentation: https://docs.gravitee.io/am/current/am_userguide_enterprise_identity_provider_saml2.html
