### ISSUE TITLE
Broken link on API management v1.x documentation (publish documentation)

### ISSUE THREAD

**Issue by romsDKT** [gravitee-io/gravitee-docs#222]
Hi Gravitee team,

I've noticed a broken link on API management v1.x documentation.
When you click on API publishers guide / publish documentation it redirects to: https://docs.gravitee.io/apim/1.x/apim_publisherguide_publish_documentation.html -> 404

![image](https://user-images.githubusercontent.com/47742357/93067982-2d9f1780-f67c-11ea-8a11-e49c93c7dc43.png)

Regards,

**Comment by phiz71** [comment]
Hi @romsDKT, thank you. That will be fixed with next release of APIM.
