### ISSUE TITLE
For Swagger 2.0 and OAI 3.0 versions, we can user vendor extensions. So I will add a `x-gravitee` extension at the root level.

### ISSUE THREAD

**Issue by ahmadajlony** [gravitee-io/gravitee-docs#238]
For Swagger 2.0 and OAI 3.0 versions, we can user vendor extensions. So I will add a `x-gravitee` extension at the root level.

In this extension, user will be able to configure these fields : 
- `categories` : String[]
- `contextPath` : String
- `groups` : String[]
- `labels` : String[]
- `metadata` : [ {key, value} ]
- `picture` : String
- `pictureURL` : String
- `properties` : [ {key, value} ]
- `tags` : String[]
- `visibility` : Enum (PRIVATE or PUBLIC)

_Originally posted by @phiz71 in https://github.com/gravitee-io/issues/issue_comments/699950850_

**Comment by aelamrani** [comment]
Hi @ahmadajlony 

What is the purpose of this issue?

As this is basically a copy paste of another issue (https://github.com/gravitee-io/issues/issues/4295) and the documentation will be part of it.

So closing it, reopen if I miss something here.
