### ISSUE TITLE
Update Kubernetes Install Guide 

### ISSUE THREAD

**Issue by tiffanymarchi** [gravitee-io/gravitee-docs#499]
Per Elesh, we should update the docs to include the config for JDBC (postgres)

___

Message from Elesh for context: [They] "Just requested that we update the Install Guide for the JDBC Connector with the K8s Helm charts - as they were experiencing a lots of problem hooking up Postgres instead of MongoDB (they were a bit upset at the errors they were experiencing)"

**Comment by apoddany** [comment]
Note: especially on PostgreSQL (AuroraDB).. As the current JDBC setup launches an init container that fetches a mysql jdbc connector jar.

**Comment by tiffanymarchi** [comment]
Fix helm chart and instructions on both gravitee.io (also, update dynamic button as we currently have the helm chart for AE mislabelled as the helm chart for APIM on the downloads page) and docs.gravitee.com.

See: https://www.gravitee.io/downloads/api-management
___
Have currently reached out to Webflow support for assistance with dynamic for Kubernetes helm chart on downloads page.

**Comment by tiffanymarchi** [comment]
Also, update website to include all proper versions of products (APIM, AM, AE, Cockpit).

**Comment by tiffanymarchi** [comment]
@aelamrani and dev team have planned this into their current sprint, and this info should be delivered to me sometime during the week starting 23 Aug.

**Comment by plsstephenson** [comment]
Done: https://docs.gravitee.io/apim/3.x/apim_installguide_kubernetes.html#postgressql_via_jdbc_connection
