### ISSUE TITLE
Typo on https://docs.gravitee.io/apim/3.x/apim_quickstart_publish_api.html

### ISSUE THREAD

**Issue by gravitee-eleshmistry** [gravitee-io/gravitee-docs#619]
On the following page there is a typo : 

Problems while working with the API

Problem Publishing an API
On this url I found a typo: https://docs.gravitee.io/apim/3.x/apim_quickstart_publish_api.html

![image](https://user-images.githubusercontent.com/85284205/145258925-9510bf04-1905-4437-bb22-b01ad859656f.png)

It should be lifecycle_state instead of lifecyle_state.

**Comment by plsstephenson** [comment]
Fixed
