### ISSUE TITLE
Example on Consuming an API with APIM API Docs Page is incorrect

### ISSUE THREAD

**Issue by gravitee-eleshmistry** [gravitee-io/gravitee-docs#620]
On this page - https://docs.gravitee.io/apim/3.x/apim_quickstart_consume_api.html

the example says 

```
curl -H "Authorization: Basic **************=" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '{"name":"My first Application","type":"Web","description":"Web client for Gravitee.io Echo API"}' \
     http://MANAGEMENT_API_SERVER_DOMAIN/portal/environments/DEFAULT/applications
```

But I believe this structure is correct 

```
curl -ki -H "Authorization: Basic $lmA_AUTH" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '
       { "name": "app3","description": "My app3",
         "settings": { "app": { "type": "web" } }
       }
       ' \
     https://apim.****.aws.local/portal/environments/DEFAULT/applications
```

**Comment by mouligno** [comment]
@gravitee-eleshmistry i don't see what you want to update ?

**Comment by gravitee-eleshmistry** [comment]
Yep the example in the documentation does not work and the example I shared does work

**Comment by siongravitee** [comment]
@gravitee-eleshmistry are you able to provide a generic example that can be used in the documentation?

**Comment by gravitee-eleshmistry** [comment]
Hi @siongravitee - We can use this

curl -ki -H "Authorization: Basic $lmA_AUTH" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '
       { "name": "app3","description": "My app3",
         "settings": { "app": { "type": "web" } }
       }
       ' \
     https://apim.****.aws.local/portal/environments/DEFAULT/applications
