### ISSUE TITLE
[policy] Policy instance creation rules

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/gravitee-docs#69]
see gravitee-io/issues#460

**Comment by plsstephenson** [comment]
@brasseld Please can you confirm it is ok to close the issue? The cache resource/policy is covered here: https://docs.gravitee.io/apim/3.x/apim_publisherguide_design_studio_create.html#create-resources and here: https://docs.gravitee.io/apim/3.x/apim_policies_cache.html
