### ISSUE TITLE
Circuit Breaker policy - missing documentation

### ISSUE THREAD

**Issue by tech-Nico** [gravitee-io/gravitee-docs#843]
Gravitee provides a [Circuit Breaker](https://github.com/gravitee-io/gravitee-policy-circuit-breaker) policy that allows switching to a different URL when the backend does not respond or responds too slowly.
This policy does not have any documentation and I think it's a very important policy that Gravitee feature.
Explain:
- What the policy does
- When it should/should not be used
- How it is configured and the impact of each configuration field.

**Comment by ivan-gravitee** [comment]
Docs updated in [repo](https://github.com/gravitee-io/gravitee-policy-circuit-breaker/blob/master/README.adoc) and [docs site](https://docs.gravitee.io/apim/3.x/apim_policies_circuit_breaker.html).
